trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

pool:
  vmImage: 'ubuntu-latest'
steps:
- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'specific'
    project: 'simple-it'
    pipeline: 1
    buildVersionToDownload: 'latest'
  displayName: Download server artifact
- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'specific'
    project: 'simple-it'
    pipeline: 2
    buildVersionToDownload: 'latest'
  displayName: Download client artifact
- task: Docker@2
  displayName: Build docker image
  inputs:
    command: build
    dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    tags: |
      $(tag)